services:
  mymail:
    build: .
    working_dir: /usr/src/mymail
    restart: unless-stopped
    command: npm run start
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/mymail
      - /usr/src/mymail/node_modules 
      - .env:/usr/src/mymail/.env
      
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
  database:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5435:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "8081:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_USER: ${DB_USER}
  #     GF_SECURITY_ADMIN_PASSWORD: ${DB_PASSWORD}
  #     GF_SECURITY_ADMIN_EMAIL: "admin@example.com"  # Optional email
  #     GF_SECURITY_ALLOW_EMBEDDING: true
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - database

volumes:
  db_data:
  be_data:
  # grafana-data:

