export const TypeFieldData = [
  {
    name: "String",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: true,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Number",
    isFile: false,
    isDate: false,
    isNumber: true,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "TextArea",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: true,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Checkbox",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Dropdown",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "File",
    isFile: true,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Excel",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Photo",
    isFile: false,
    isDate: false,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: true,
    isFloat: false,
    isDelete: false,
  },
  {
    name: "Date",
    isFile: false,
    isDate: true,
    isNumber: false,
    isText: false,
    isTextArea: false,
    isImage: false,
    isFloat: false,
    isDelete: false,
  },
];
